# Pandas Basics
---
In this notebook, we will learn about the Pandas library, which is not a library about animals, but about working with [**pan**el **da**ta](https://en.wikipedia.org/wiki/Panel_data).

Pandas leverages many of the concepts and features of NumPy, and is built on top of it. Great! All we have learned last week will be useful today. On the other hand, if you skipped last week's class and you are not yet familiar with NumPy, this notebook will be a bit more challenging and you should go back to the previous notebook and work through it before proceeding.

## DataFrames
---
Just like NumPy had `np.ndarray` as its core data structure, Pandas has `pd.DataFrame` as its core data structure. Typically, you can think of a `pd.DataFrame` as a table with rows and columns, e.g.,

| Name | Age | Gender | Height |
| --- | --- | --- | --- |
| Alice | 25 | Female | 165 |
| Bob | 30 | Male | 175 |
| Charlie | 35 | Male | 172 |

Each row in the table represents a case, and each column represents a variable. A *variable* is just a piece of information you record about each case in your data. In data science, we typically call the cases *observations*. Variables are also called *features* or *attributes*. 

Pandas and NumPy play well together. In fact, you can think of a `pd.DataFrame` as a generalization of a 2D NumPy array. In particular, columns of a DataFrame can be of different types, not necessarily just numbers.

You can also create a DataFrame from a NumPy array and vice versa, as we will see below.

In [1]:
# Import NumPy as we learned previously
import numpy as np

# Now we also import Pandas under the alias pd, which is the standard alias
import pandas as pd

In [2]:
# Create a 2D numpy array (2 rows, 3 columns)
X = np.array([[1, 2, 3], [4, 5, 6]])

# Create a DataFrame from the numpy array
df = pd.DataFrame(X)

# Display the DataFrame
df

   0  1  2
0  1  2  3
1  4  5  6

We can also pass column names and row indices to the `pd.DataFrame` constructor.

In [3]:
df = pd.DataFrame(X, columns=['X', 'Y', 'Z'], index=['i', 'j'])
df

   X  Y  Z
i  1  2  3
j  4  5  6

As we mentioned above, Pandas and NumPy play well together. We can also reuse some of what we learned last week, notice however that there are also some differences.

In [4]:
# Similar to NumPy, we have access to the shape of the DataFrame
df.shape

(2, 3)

In [5]:
# We can also compute the mean, but notice how the default is column-wise!
df.mean()

X    2.5
Y    3.5
Z    4.5
dtype: float64

That means are column-wise is exactly what we need in practical data science work.

In advanced cases, it can happen that you need to convert a dataframe into a numpy array. This can be done as follows.

In [6]:
# The recommended way to convert a dataframe to a numpy array
df.to_numpy()

array([[1, 2, 3],
       [4, 5, 6]])

## Loading Data
---

While programming and mathematics are fun in their own right, this class is about data science and thus, we will now start working with data.

Data can be stored in a variety of formats. Most commonly, you will encounter CSV which stands for Comma-Separated Values. This is a text-based format that is used to store tabular data, such as a spreadsheet or a database.

CSVs are plain text files, which makes them easy to read and write to. It also means that they are readable by any text editor and we can open them with Excel as well.

We will be working with the [Iris dataset](https://en.wikipedia.org/wiki/Iris_flower_data_set), which is a classic dataset in pattern recognition and statistics. Many data scientists have made their first steps using this dataset. It contains measurements of the sepal length, sepal width, petal length, and petal width of 150 iris flowers, together with their species.


If you don't know what petals and sepals are, here is an illustration:
![](https://cdn.britannica.com/39/91239-004-44353E32/Diagram-flowering-plant.jpg)

In [7]:
# Loading a CSV file is as easy as calling pd.read_csv
df = pd.read_csv("data/iris.csv")

# Show the first 10 rows of the dataframe (use df.tail(n) to show the last n rows)
df.head(10)

,species,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,virginica,7.7,2.6,6.9,2.3
1,virginica,7.7,3.8,6.7,2.2
2,virginica,7.7,2.8,6.7,2.0
3,setosa,4.6,3.6,1.0,0.2
4,setosa,4.3,3.0,1.1,0.1
5,setosa,5.8,4.0,1.2,0.2
6,setosa,5.0,3.2,1.2,0.2
7,setosa,5.4,3.9,1.3,0.4
8,setosa,4.7,3.2,1.3,0.2
9,setosa,4.4,3.2,1.3,0.2

When you load a file in Python with something like `pd.read_csv("data/iris.csv")`, the expression `"data/iris.csv"` is called a **relative path**. That means Python starts looking for files in what is called the **current working directory** (that is the default "starting folder" or "home" for your Jupyter notebook). In our setup on Nuvolos, that directory is called `"files"`. From there, the path says: go into the subfolder called `"data"` and then open the file named `"iris.csv"`. The path `"data/iris.csv"` doesn't describe the file's full location (on Nuvolos or your computer), but only where to find it **relative to the starting folder**. This is the most common way to indicate the location from where to read a file.

You will learn more about relative and absolute paths in notebook nr. 4 on data handling.

Notice that we have a total of 5 columns with 4 of them being numeric and one, i.e. `species`, being a string.

So if we were to try `df.mean()`, we would get an error, as we cannot compute the mean of a non-numeric column.

However, there is a useful method called `.describe()` that will give us a summary statistics of all numerical columns without us having to specify which columns we want to ignore.

In [8]:
# Describe will give us the summary statistics
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

What about the `species` column? What type of statistics can we be interested in for a categorical column?

Well, one thing we could be interested in is the number of samples per category. We can do this by calling the `.value_counts()` method on the column.

In [9]:
# Count the number of observations (rows) per category
df["species"].value_counts()

species
virginica     50
setosa        50
versicolor    50
Name: count, dtype: int64

Also extremely useful is to find out which categories we actually have. For this, we use the `.unique()` method.

In [10]:
df["species"].unique()

array(['virginica', 'setosa', 'versicolor'], dtype=object)

Notice how we accessed the `species` column as we would access a dictionary key. If we want to select multiple columns, we can pass a list instead of a single string.

In [11]:
# Select two columns by passing a list as a key
df[["species", "sepal length (cm)"]]

        species  sepal length (cm)
0     virginica                7.7
1     virginica                7.7
2     virginica                7.7
3        setosa                4.6
4        setosa                4.3
..          ...                ...
145  versicolor                5.7
146  versicolor                5.7
147  versicolor                6.2
148  versicolor                5.1
149  versicolor                5.7

[150 rows x 2 columns]

Sometimes, it's easier to access the columns using their number instead of their names, we can use the `.columns` attribute to do so.

In [12]:
# Select the first two columns
df[df.columns[:2]]

        species  sepal length (cm)
0     virginica                7.7
1     virginica                7.7
2     virginica                7.7
3        setosa                4.6
4        setosa                4.3
..          ...                ...
145  versicolor                5.7
146  versicolor                5.7
147  versicolor                6.2
148  versicolor                5.1
149  versicolor                5.7

[150 rows x 2 columns]

Lastly, we can also drop specific columns.

In [13]:
# Select all columns except the sepal length and width columns
df.drop(columns=["sepal length (cm)", "sepal width (cm)"])

        species  petal length (cm)  petal width (cm)
0     virginica                6.9               2.3
1     virginica                6.7               2.2
2     virginica                6.7               2.0
3        setosa                1.0               0.2
4        setosa                1.1               0.1
..          ...                ...               ...
145  versicolor                4.2               1.2
146  versicolor                4.2               1.3
147  versicolor                4.3               1.3
148  versicolor                3.0               1.1
149  versicolor                4.1               1.3

[150 rows x 3 columns]

#### ➡️ ✏️ Your turn 

Compute the 10th percentile of all numeric columns.

*Hint*: Pandas has a `.quantile(q)` method that can be used to compute the q-th quantile of a column. Do you remember the relationship between quantiles and percentiles?

In [14]:
# ➡️ Your code here...

In [15]:
# SOLUTION
df.drop(columns = ["species"]).quantile(.1)

sepal length (cm)    4.8
sepal width (cm)     2.5
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0.1, dtype: float64

## Subsetting Data
---

So far, we have seen how to load data from a CSV file and how to select particular columns. Of course, this is not enough for real-world data analysis tasks. More often than not, we want to select rows based on certain conditions, e.g., we might want to select all observations for a given species or all observations with a sepal length greater than a certain value.

Recall how in NumPy we indexed our arrays as follows:

```python
X[row_indices, column_indices]
```

In Pandas, we can do the same using the `.loc` accessor, which allows us to select rows and columns by their index.

```python
df.loc[row_indices, column_indices]
```

We can also use the `.iloc` accessor, which allows us to select rows and columns by their integer location.

```python
df.iloc[row_indices, column_indices]
```

This can be slightly confusing at first, so let's make sure we understand the difference between the two.

In [16]:
# Let us print the first 5 rows for reference
df.head(5)

,species,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,virginica,7.7,2.6,6.9,2.3
1,virginica,7.7,3.8,6.7,2.2
2,virginica,7.7,2.8,6.7,2.0
3,setosa,4.6,3.6,1.0,0.2
4,setosa,4.3,3.0,1.1,0.1

In [17]:
# Access the observation with index 0
df.loc[0, :]

species              virginica
sepal length (cm)          7.7
sepal width (cm)           2.6
petal length (cm)          6.9
petal width (cm)           2.3
Name: 0, dtype: object

In [18]:
# Access the observation in the 0th row
df.iloc[0, :]

species              virginica
sepal length (cm)          7.7
sepal width (cm)           2.6
petal length (cm)          6.9
petal width (cm)           2.3
Name: 0, dtype: object

But these are the same?! That is because, in this case, the index and the row number are the same. But wait, this is more tricky than it looks, as they are not always the same...

⚠️ Be very careful with `.loc` and `.iloc` as they generally behave differently. In truth, it's very rare that you will need to use `.iloc` as it is more error-prone. We typically want to access rows by their index, not by their position.

In [19]:
# An example where they differ
df2 = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]}, index=[1, 2, 3])
df2

   A  B
1  1  4
2  2  5
3  3  6

In [20]:
# Access the observation with index 1, notice this is the 0th row
df2.loc[1, :]

A    1
B    4
Name: 1, dtype: int64

In [21]:
# Access the observation in the 1st row, this is the index 2!
df2.iloc[1, :]

A    2
B    5
Name: 2, dtype: int64

#### 🤔 The beauty of indices

It can take a while to appreciate the power of indices and they can be tricky to understand at first. However, as you proceed in your data science journey, you will come to find that indices are a very powerful tool to have in your disposal.

For instance, indices need not be numbers from 0 to N-1, but can be any value we want, e.g., when working with time-series data, we will often use the date as the index, which will allow us to instantly select observations for a given date or even a range of dates. But these are more advanced topics that we will not cover here. However, they might come up in your projects, so you can always come back to this notebook for reference.

🙀 🤯 Don't worry about the `pd.to_datetime` function for now, we will see more of it in the next notebooks.

```python 
# Create a dataframe with dates as the index
df3 = pd.DataFrame({"A": [1, 2, 3]}, index=pd.to_datetime(["2020-01-01", "2020-01-02", "2020-01-03"]))

# Access the observation with index '2020-01-01'
df3.loc["2020-01-01", :]
```

Okay, once again, a quick recap is in order. We have seen how to select columns and rows in a dataframe. In particular, we can select rows by their index using the `.loc` accessor.

In practice, it occurs more often that we would like to filter rows based on certain conditions. We have already done this with NumPy. For instance, we might want to select all observations for a given species, say the species **virginica**.

In [22]:
df["species"] == "virginica"

0       True
1       True
2       True
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: species, Length: 150, dtype: bool

We may want to know the type of this object that we just calculated

In [23]:
# You have learned to use the type function
type(df["species"]=="virginica")

pandas.core.series.Series

Hm, that is not very informative. In Pandas, you should inquire types of dataframe objects using dtype().

In [24]:
(df["species"]=="virginica").dtype

dtype('bool')

In [25]:
# We can also use 
df.dtypes

species               object
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object

So `df["species"]=="virginica"` is a column of booleans. We can use it to filter only the virginica observations. In the jargon of NumPy, Pandas, and more generally array programming, we call the boolean `df["species"]=="virginica"` a **mask**.

In [26]:
df[df["species"]=="virginica"]

,species,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,virginica,7.7,2.6,6.9,2.3
1,virginica,7.7,3.8,6.7,2.2
2,virginica,7.7,2.8,6.7,2.0
53,virginica,4.9,2.5,4.5,1.7
54,virginica,6.0,3.0,4.8,1.8
55,virginica,6.2,2.8,4.8,1.8
56,virginica,5.6,2.8,4.9,2.0
57,virginica,6.3,2.7,4.9,1.8
58,virginica,6.1,3.0,4.9,1.8
59,virginica,6.0,2.2,5.0,1.5
60,virginica,5.7,2.5,5.0,2.0
61,virginica,6.3,2.5,5.0,1.9
62,virginica,5.8,2.7,5.1,1.9
63,virginica,5.8,2.8,5.1,2.4
64,virginica,6.9,3.1,5.1,2.3
65,virginica,6.3,2.8,5.1,1.5
66,virginica,5.9,3.0,5.1,1.8
67,virginica,5.8,2.7,5.1,1.9
68,virginica,6.5,3.2,5.1,2.0
69,virginica,6.7,3.0,5.2,2.3
70,virginica,6.5,3.0,5.2,2.0
71,virginica,6.4,2.7,5.3,1.9
72,virginica,6.4,3.2,5.3,2.3
73,virginica,6.9,3.1,5.4,2.1
74,virginica,6.2,3.4,5.4,2.3
75,virginica,6.5,3.0,5.5,1.8
76,virginica,6.4,3.1,5.5,1.8
77,virginica,6.8,3.0,5.5,2.1
78,virginica,6.4,2.8,5.6,2.2
79,virginica,6.7,3.1,5.6,2.4
80,virginica,6.4,2.8,5.6,2.1
81,virginica,6.3,3.4,5.6,2.4
82,virginica,6.1,2.6,5.6,1.4
83,virginica,6.3,2.9,5.6,1.8
84,virginica,6.9,3.2,5.7,2.3
85,virginica,6.7,3.3,5.7,2.5
86,virginica,6.7,3.3,5.7,2.1
87,virginica,6.7,2.5,5.8,1.8
88,virginica,7.2,3.0,5.8,1.6
89,virginica,6.5,3.0,5.8,2.2
90,virginica,7.1,3.0,5.9,2.1
91,virginica,6.8,3.2,5.9,2.3
92,virginica,7.2,3.2,6.0,1.8
93,virginica,6.3,3.3,6.0,2.5
94,virginica,7.7,3.0,6.1,2.3
95,virginica,7.2,3.6,6.1,2.5
96,virginica,7.4,2.8,6.1,1.9
97,virginica,7.3,2.9,6.3,1.8
98,virginica,7.9,3.8,6.4,2.0
99,virginica,7.6,3.0,6.6,2.1

This filters all rows for which the boolean `df["species"]=="virginica"` is true. Does the image of a "mask" make sense to you? How?

Filtering with masks is very flexible. Here is another example.

In [27]:
# Select all observations for the species virginica
df[df["sepal length (cm)"] >= 5.5]

,species,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,virginica,7.7,2.6,6.9,2.3
1,virginica,7.7,3.8,6.7,2.2
2,virginica,7.7,2.8,6.7,2.0
5,setosa,5.8,4.0,1.2,0.2
13,setosa,5.5,3.5,1.3,0.2
...,...,...,...,...,...
144,versicolor,5.6,2.7,4.2,1.3
145,versicolor,5.7,3.0,4.2,1.2
146,versicolor,5.7,2.9,4.2,1.3
147,versicolor,6.2,2.9,4.3,1.3
149,versicolor,5.7,2.8,4.1,1.3

Let's check that this worked.

In [28]:
df[df["sepal length (cm)"] >= 5.5]["sepal length (cm)"].min()

5.5

This was a terribly compact piece of code. Can you decipher it?

⚠️ Notice that we didn't use the `.loc` accessor here. However, we could have! Let's see how.

In [29]:
df.loc[df["sepal length (cm)"]>=5.5]

,species,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,virginica,7.7,2.6,6.9,2.3
1,virginica,7.7,3.8,6.7,2.2
2,virginica,7.7,2.8,6.7,2.0
5,setosa,5.8,4.0,1.2,0.2
13,setosa,5.5,3.5,1.3,0.2
...,...,...,...,...,...
144,versicolor,5.6,2.7,4.2,1.3
145,versicolor,5.7,3.0,4.2,1.2
146,versicolor,5.7,2.9,4.2,1.3
147,versicolor,6.2,2.9,4.3,1.3
149,versicolor,5.7,2.8,4.1,1.3

The code works just the same. Whether you include the `.loc` or not, the result is the same. So why bother about `.loc`? Well, somtimes, we may want to select both certain columns and certain rows. **If we want to select rows and columns in one go, we must use the `.loc` accessor.** The pattern of how to do it is the same as NumPy, we separate the row condition and the column condition with a comma:

```python
df.loc[row_condition, column_condition]
```
Let's look at an example.

In [30]:
# Obtain only the sepal length and width for the virginica species
df.loc[df["species"] == "virginica", ["species", "sepal length (cm)", "sepal width (cm)"]]

      species  sepal length (cm)  sepal width (cm)
0   virginica                7.7               2.6
1   virginica                7.7               3.8
2   virginica                7.7               2.8
53  virginica                4.9               2.5
54  virginica                6.0               3.0
55  virginica                6.2               2.8
56  virginica                5.6               2.8
57  virginica                6.3               2.7
58  virginica                6.1               3.0
59  virginica                6.0               2.2
60  virginica                5.7               2.5
61  virginica                6.3               2.5
62  virginica                5.8               2.7
63  virginica                5.8               2.8
64  virginica                6.9               3.1
65  virginica                6.3               2.8
66  virginica                5.9               3.0
67  virginica                5.8               2.7
68  virginica                6.5               3.2
69  virginica                6.7               3.0
70  virginica                6.5               3.0
71  virginica                6.4               2.7
72  virginica                6.4               3.2
73  virginica                6.9               3.1
74  virginica                6.2               3.4
75  virginica                6.5               3.0
76  virginica                6.4               3.1
77  virginica                6.8               3.0
78  virginica                6.4               2.8
79  virginica                6.7               3.1
80  virginica                6.4               2.8
81  virginica                6.3               3.4
82  virginica                6.1               2.6
83  virginica                6.3               2.9
84  virginica                6.9               3.2
85  virginica                6.7               3.3
86  virginica                6.7               3.3
87  virginica                6.7               2.5
88  virginica                7.2               3.0
89  virginica                6.5               3.0
90  virginica                7.1               3.0
91  virginica                6.8               3.2
92  virginica                7.2               3.2
93  virginica                6.3               3.3
94  virginica                7.7               3.0
95  virginica                7.2               3.6
96  virginica                7.4               2.8
97  virginica                7.3               2.9
98  virginica                7.9               3.8
99  virginica                7.6               3.0

#### ➡️ ✏️ Your turn 

1. Compute the mean sepal length for the virginica species and for the setosa species, which species has a larger sepal length on average?
2. For the versicolor species, compute a rough estimate of the petal area, which you may assume to be the product of the petal length and width. What is the mean petal area for the versicolor species? *Hint*: You can work do mathematical operations in Pandas just as you would do in NumPy.

In [31]:
# ➡️ Your code here...

In [32]:
# SOLUTION to 1.
display( 
        df.loc[df["species"]=="virginica", ["sepal length (cm)"]].mean()
)

display( 
        df.loc[df["species"]=="setosa", ["sepal length (cm)"]].mean()
)

sepal length (cm)    6.588
dtype: float64

sepal length (cm)    5.006
dtype: float64

In [33]:
# SOLUTION to 2.
(
    df.loc[df["species"]=="versicolor", "petal length (cm)"] * df.loc[df["species"]=="versicolor", "petal width (cm)"]
    ).mean()

5.7204

Finally, we close this section by learning how to add new columns to a dataframe. This is a task we will often want to do and it is very easy to do in Pandas.

We will add a new column called `petal area` to our dataframe which consists of the product of the petal length and width.

In [34]:
# Add a new column called petal area to the dataframe
df["petal area"] = df["petal length (cm)"] * df["petal width (cm)"]

# Show the first 5 rows of the dataframe
df.head(5)

,species,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),petal area
0,virginica,7.7,2.6,6.9,2.3,15.87
1,virginica,7.7,3.8,6.7,2.2,14.74
2,virginica,7.7,2.8,6.7,2.0,13.40
3,setosa,4.6,3.6,1.0,0.2,0.20
4,setosa,4.3,3.0,1.1,0.1,0.11

## Grouping and Aggregation
---

Today's last topic is grouping and aggregation. This is where the true power of Pandas gets to shine.

It was a bit tideous to compute the mean for each individual species above. Of course, now that you know enough Python, you might come up with the idea to use a for-loop to iterate over the species and compute the mean sepal length for each species, which is not a bad idea at all. However, Pandas provides us with a more convenient way to do this, which uses the concept of *grouping* and *aggregating*.

Grouping and aggregating go hand in hand. We can think of *grouping* as the process of dividing data into groups based on certain criteria, while *aggregating* is the process of applying a function to each group and aggregating the different sub-groups back into a single object.

🙀 🤯 Sometimes, we only want to group without aggregating. There are good reasons to do this, but this is a more advanced topic that you will probably not need for a while. As such we don't cover it here and you might not see it until much later down your data science path.

So how would we go about computing the mean sepal length for each species using these new concepts? It's actually pretty straightforward, just remember the two steps:

1. Group the data by a specified column (or multiple columns).
2. Apply a function to each group or to specific columns in each group.

In [35]:
# Step 1: Group the data by the species column
dfg = df.groupby("species")

# Step 2: Apply the mean function to the sepal length column
dfg["sepal length (cm)"].mean()

species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepal length (cm), dtype: float64

Et voilà! We have computed the mean sepal length for each species. Of course, we can also write the above code a bit more concisely by chaining the methods together.

In [36]:
df.groupby("species")["sepal length (cm)"].mean()

species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepal length (cm), dtype: float64

&hellip; and we get the same result. Moreover, we can compute the mean sepal width for each species at the same time!

In [37]:
# Notice the double brackets, this is because the key is a list!
df.groupby("species")[["sepal length (cm)", "sepal width (cm)"]].mean()

            sepal length (cm)  sepal width (cm)
species
setosa                  5.006             3.428
versicolor              5.936             2.770
virginica               6.588             2.974

&hellip; and we could also apply the mean to all the columns at once.

In [38]:
df.groupby("species").mean()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),petal area
species,,,,,
setosa,5.006,3.428,1.462,0.246,0.3656
versicolor,5.936,2.770,4.260,1.326,5.7204
virginica,6.588,2.974,5.552,2.026,11.2962

Of course, we can also apply other aggregation functions, such as the sum, max, min, etc.

In [39]:
# Find the maximum value for each column by species
df.groupby("species").max()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),petal area
species,,,,,
setosa,5.8,4.4,1.9,0.6,0.96
versicolor,7.0,3.4,5.1,1.8,8.64
virginica,7.9,3.8,6.9,2.5,15.87

In [40]:
# Find the standard deviation for each column by species
df.groupby("species").std()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),petal area
species,,,,,
setosa,0.352490,0.379064,0.173664,0.105386,0.181155
versicolor,0.516171,0.313798,0.469911,0.197753,1.368403
virginica,0.635880,0.322497,0.551895,0.274650,2.157412

Lastly, we can also be more creative with our aggregation functions. For instance, we may want to compute both the mean and the standard deviation of the sepal length for each species. We cannot do this easily with the methods we have been using so far, but we can use the `.agg` method to achieve this.

In [41]:
df.groupby("species")["sepal length (cm)"].agg(["mean", "std"])

             mean       std
species
setosa      5.006  0.352490
versicolor  5.936  0.516171
virginica   6.588  0.635880

Notice that we have passed a list of aggregation functions (strings that represent method names, to be precise) to the `.agg` method.

Finally, we can also apply different aggregation functions to different columns. To do so, we simply pass a dictionary to the `.agg` method, with the keys being the columns and the values being the aggregation functions.

In [42]:
df.groupby("species").agg({
    "sepal length (cm)": ["mean", "std"],
    "sepal width (cm)": ["min", "max"],
    "petal length (cm)": "median"
})

           sepal length (cm)           sepal width (cm)      petal length (cm)
                        mean       std              min  max            median
species
setosa                 5.006  0.352490              2.3  4.4              1.50
versicolor             5.936  0.516171              2.0  3.4              4.35
virginica              6.588  0.635880              2.2  3.8              5.55

#### ➡️ ✏️ Your turn 

1. Compute the mean and standard deviation of the petal length for each species. Does the standard deviation increase or decrease with the average petal length?
2. Add a new column called `ratio` to the dataframe that contains the ratio of the petal length to the sepal length. (`petal length / sepal length`)
3. Add a new column called `ratio_category` to the dataframe that contains the value `large` if the ratio is greater than 0.5 and `small` otherwise. *Hint*: Recall how to use `np.where` to create an array by applying an if-else condition to each element of the array.
4. Group by the list `["species", "ratio_category"]` and compute the mean sepal width for each group. Does the sepal width increase or decrease with the petal length ratio?

In [43]:
# ➡️ Your code here...

In [44]:
# SOLUTION to 1.
df.groupby("species")["petal length (cm)"].agg(["mean", "std"])

             mean       std
species
setosa      1.462  0.173664
versicolor  4.260  0.469911
virginica   5.552  0.551895

In [45]:
# SOLUTION to 2.
df["ratio"] = df["petal length (cm)"] / df["sepal length (cm)"]

In [46]:
# SOLUTION to 3.
df["ratio_category"] = np.where(df["ratio"]>0.5, "large", "small")
df.head()

,species,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),petal area,ratio,ratio_category
0,virginica,7.7,2.6,6.9,2.3,15.87,0.896104,large
1,virginica,7.7,3.8,6.7,2.2,14.74,0.870130,large
2,virginica,7.7,2.8,6.7,2.0,13.40,0.870130,large
3,setosa,4.6,3.6,1.0,0.2,0.20,0.217391,small
4,setosa,4.3,3.0,1.1,0.1,0.11,0.255814,small

In [47]:
# SOLUTION to 4.
df.groupby(["species", "ratio_category"])["sepal width (cm)"].mean()

species     ratio_category
setosa      small             3.428
versicolor  large             2.770
virginica   large             2.974
Name: sepal width (cm), dtype: float64